project_id = "ejrttghgscfhbezvobhv"

[functions.rukisha-ai]
verify_jwt = false

[functions.bank-merchant-sync]
verify_jwt = false

[functions.settlement-midnight-run]
verify_jwt = false

[functions.bank-simulator]
verify_jwt = false

[functions.switch-process-intent]
verify_jwt = false
